// angular/src/app/realgrid/realgrid.component.ts
import { Component, OnInit } from '@angular/core';
import { GridView, LocalDataProvider } from 'realgrid';
import { columns, rows, fields } from './realgrid-data';

let gridView: GridView, dataProvider: LocalDataProvider;

@Component({
  selector: 'app-realgrid',
  templateUrl: './realgrid.component.html',
  styleUrls: ['./realgrid.component.css']
})

export class RealgridComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

document.addEventListener('DOMContentLoaded', function () {
  dataProvider = new LocalDataProvider(false);
  gridView = new GridView("realgrid");
  gridView.setDataSource(dataProvider);

  dataProvider.setFields(fields);
  gridView.setColumns(columns);

  const button = document.getElementById('loaddata');

  if (button) {
      button.onclick = loadData;
  }
});

const loadData = function() {
  dataProvider.setRows(rows);
}
<p>realgrid works!</p>
<div id="realgrid"></div>
<button id='loaddata'>Load Data!</button>

// vue3-2grid-sample/src/components/RealGrid.vue
<template>
  <div class="real">
    <div :id="gridName" style="width: 100%; height: 400px"></div>
    <button @click="loadData">load data~~!!</button>
  </div>
</template>


<script>
import { GridView, LocalDataProvider } from 'realgrid';
import { columns, fields, rows } from './realgrid-data';

export default {
  name: 'RealGrid',
  props: ["domName"],
  data: function () {
      return {
          gridName: this.domName,
          gv: null,
          dp: null,
      }
  },
  methods: {
      loadData: function() {
          this.dp.setRows(rows);
      }
  },
  mounted() {
    console.log(this.gridName);
    this.dp = new LocalDataProvider(false);
    this.gv = new GridView(this.gridName);
    
    this.gv.setDataSource(this.dp);

    this.dp.setFields(fields);
    this.gv.setColumns(columns);
  }
}
</script>
