// angular/src/app/realgrid/realgrid.component.ts
import { Component, OnInit } from '@angular/core';
import { GridView, LocalDataProvider } from 'realgrid';
import { columns, rows, fields } from './realgrid-data';

let gridView: GridView, dataProvider: LocalDataProvider;

@Component({
  selector: 'app-realgrid',
  templateUrl: './realgrid.component.html',
  styleUrls: ['./realgrid.component.css']
})

export class RealgridComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

document.addEventListener('DOMContentLoaded', function () {
  dataProvider = new LocalDataProvider(false);
  gridView = new GridView("realgrid");
  gridView.setDataSource(dataProvider);

  dataProvider.setFields(fields);
  gridView.setColumns(columns);

  const button = document.getElementById('loaddata');

  if (button) {
      button.onclick = loadData;
  }
});

const loadData = function() {
  dataProvider.setRows(rows);
}
<p>realgrid works!</p>
<div id="realgrid"></div>
<button id='loaddata'>Load Data!</button>

// vue3-typescript-vite/src/components/RealGrid.vue
<template>
  <div id="realgrid" style="width: 100%; height: 400px"></div>
  <button @click="loadData">데이터 생성하기</button>
</template>


<script lang="ts"> 
import { GridView, LocalDataProvider } from "realgrid";
import { columns, fields, rows } from "./realgrid-data";

let gridView: GridView; 
let dataProvider: LocalDataProvider;
export default {
  name: "RealGrid",
  setup() {
    return {};
  },
  methods: {
    loadData() {
      dataProvider.setRows(rows);
    },
  },
  mounted() {
    dataProvider = new LocalDataProvider(false);
    gridView = new GridView("realgrid");
    gridView.setDataSource(dataProvider);
    dataProvider.setFields(fields);
    gridView.setColumns(columns);

    
  },
};
</script>
